"""DOCX and PDF generation from a Markdown-ish structured text."""
from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, Inches
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)


def _parse_blocks(text: str) -> list[tuple[str, str]]:
    """Return list of (kind, text) where kind ∈ {h1, h2, h3, li, p}."""
    blocks: list[tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            blocks.append(("blank", ""))
            continue
        if line.startswith("# "):
            blocks.append(("h1", line[2:].strip()))
        elif line.startswith("## "):
            blocks.append(("h2", line[3:].strip()))
        elif line.startswith("### "):
            blocks.append(("h3", line[4:].strip()))
        elif re.match(r"^[-*•]\s+", line):
            blocks.append(("li", re.sub(r"^[-*•]\s+", "", line).strip()))
        else:
            blocks.append(("p", line.strip()))
    # collapse paragraph runs
    merged: list[tuple[str, str]] = []
    buf: list[str] = []
    for kind, val in blocks:
        if kind == "p":
            buf.append(val)
        else:
            if buf:
                merged.append(("p", " ".join(buf)))
                buf = []
            if kind != "blank":
                merged.append((kind, val))
    if buf:
        merged.append(("p", " ".join(buf)))
    return merged


# ---------------------------- DOCX -------------------------------------------
def build_docx(title: str, rules: str, structured_text: str, out_path: Path) -> None:
    doc = Document()
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = t.add_run(title)
    run.bold = True
    run.font.size = Pt(20)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run("Generated by DocuForge AI")
    sub_run.italic = True
    sub_run.font.size = Pt(10)

    doc.add_paragraph()

    blocks = _parse_blocks(structured_text)
    for kind, val in blocks:
        if kind == "h1":
            doc.add_heading(val, level=1)
        elif kind == "h2":
            doc.add_heading(val, level=2)
        elif kind == "h3":
            doc.add_heading(val, level=3)
        elif kind == "li":
            doc.add_paragraph(val, style="List Bullet")
        else:
            p = doc.add_paragraph(val)
            p.paragraph_format.space_after = Pt(6)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))


# ---------------------------- PDF --------------------------------------------
def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title", parent=base["Title"], fontSize=22, leading=26, spaceAfter=6
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor="#666666",
            alignment=1,
            spaceAfter=18,
        ),
        "h1": ParagraphStyle(
            "H1", parent=base["Heading1"], fontSize=18, leading=22, spaceBefore=14, spaceAfter=8
        ),
        "h2": ParagraphStyle(
            "H2", parent=base["Heading2"], fontSize=14, leading=18, spaceBefore=10, spaceAfter=6
        ),
        "h3": ParagraphStyle(
            "H3", parent=base["Heading3"], fontSize=12, leading=16, spaceBefore=8, spaceAfter=4
        ),
        "p": ParagraphStyle(
            "Body", parent=base["BodyText"], fontSize=11, leading=15, spaceAfter=6
        ),
        "li": ParagraphStyle(
            "Li", parent=base["BodyText"], fontSize=11, leading=15, leftIndent=14
        ),
    }


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def build_pdf(title: str, rules: str, structured_text: str, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=LETTER,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
        title=title,
        author="DocuForge AI",
    )
    s = _styles()
    flow = [
        Paragraph(_escape(title), s["title"]),
        Paragraph("Generated by DocuForge AI", s["subtitle"]),
    ]

    blocks = _parse_blocks(structured_text)
    pending_list: list[ListItem] = []

    def flush_list():
        nonlocal pending_list
        if pending_list:
            flow.append(ListFlowable(pending_list, bulletType="bullet", leftIndent=18))
            flow.append(Spacer(1, 6))
            pending_list = []

    for kind, val in blocks:
        if kind == "li":
            pending_list.append(ListItem(Paragraph(_escape(val), s["li"])))
            continue
        flush_list()
        if kind == "h1":
            flow.append(Paragraph(_escape(val), s["h1"]))
        elif kind == "h2":
            flow.append(Paragraph(_escape(val), s["h2"]))
        elif kind == "h3":
            flow.append(Paragraph(_escape(val), s["h3"]))
        else:
            flow.append(Paragraph(_escape(val), s["p"]))
    flush_list()

    doc.build(flow)
